name: deployment

on:
  push:
    branches:
      - main

  jobs:
    deploy:
      runs-on: ubuntu-20.04
      permissions: # Required if github_deployment is set to true.
        deployments: write
      steps:
        - uses: actions/checkout@v4
        - uses: givemomentum/render-deploy@v1.5.1
          with:
            service_id: ${{ secrets.RENDER_SERVICE_ID }} # required
            api_key: ${{ secrets.RENDER_API_KEY }} # required
            clear_cache: true
            wait_deploy: true
